JWT/JWT.cs
A project I'm working on needs the ability to set extra header values in generated JWTs. This implements the ability to do this by passing an `IDictionary<string, object>` into the encode function, and retains the original method signatures as overloads for backwards compatibility.
=> Add support for custom header values.

JWT/JWT.cs
A simple addition that makes the `DecodeToObject` API consistent with the regular `Decode` one.
=> Add DecodeToObject<T> overload with a byte[] key

JWT.Tests/DecodeTests.cs, JWT/JWT.cs, JWT/JWT.csproj, JWT/TokenExpiredException.cs
An expired token may need to be handled differently than a invalid signature. A distinct thrown exception makes it easier to handle that case.
Throwing "FormatException" for invalid "exp" format is more precise than throwing a generic "Exception"
=> Improve thrown exceptions. Add a distinct TokenExpiredException

JWT/JWT.cs
According to the [Member Overloading](https://msdn.microsoft.com/en-us/library/ms229029(v=vs.110).aspx) guidance.
=> Ordering overloads of Encode() and Decode(). Moving private methods to the bottom

src/JWT/JWT.cs, src/JWT/TokenExpiredException.cs
Adding more contextual information to the `TokenExpiredException` for usage by the parent application
=> Add payloadData and expiration to the TokenExpiredException exception

JWT.nuspec, src/JWT/JWT.csproj, src/JWT/JsonWebToken.cs, src/JWT/packages.config
- Setting TargetFrameworkVersion to v3.5
- Stopping using `Lazy<T>`
- Bumping nuget version to 2.2.0-beta
=> Downgrading target framework version to .NET 3.5

package.cmd, src/JWT/IBase64UrlEncoder.cs, src/JWT/JWT.csproj, src/JWT/JsonWebToken.cs, src/JWT/JwtBase64UrlEncoder.cs, src/JWT/JwtDecoder.cs, src/JWT/JwtEncoder.cs, tests/JWT.Tests/JwtDecoderTest.cs, tests/JWT.Tests/JwtEncoderTest.cs
- Adding IBase64UrlEncoder implemented by JwtBase64UrlEncoder. Calling it from JsonWebToken.Base64UrlEncode/Base64UrlDecode.
- Updating tests
=> Moving Base64UrlEncode/Base64UrlDecode to separate entity

JWT.nuspec, src/JWT/JWT.csproj, src/JWT/packages.config, tests/JWT.Tests/JWT.Tests.csproj, tests/JWT.Tests/packages.config
Based on #75 discussion.
The most important change: **removed the beta prefix**.
=> Updating Json.Net to v10, other dev/test dependencies

README.md
I added the missing `IBase64UrlEncoder` to the code samples included in the README.md file. This change is valid for at least the most current version v.2.3.0-beta.
=> README improvement: Added missing IBase64UrlEncoder to code samples

src/JWT/JwtValidator.cs, tests/JWT.Tests.Core/DecodeTests.cs, tests/JWT.Tests.Core/JwtDecoderTest.cs
Update exp and nbf validation to be based on strictly-parsed doubles for 2 reasons: Support dates beyond year 2038, and prevent treating nulls as 0.
=> Update exp and nbf validation to use double parsing

.gitignore, appveyor.yml, build.cake, build.ps1, src/JWT/JWT.csproj
Closes https://github.com/jwt-dotnet/jwt/issues/74
=> Automated builds with Cake

appveyor.yml
Minor fix: I forgot to include this in the original commit of the AppVeyor config. This will pin the AppVeyor build environment to Visual Studio 2017 (which is confirmed working), and will remove the requirement of picking this when setting up AppVeyor.
=> Explicitly specify AppVeyor build image

src/JWT/Algorithms/HMACSHAAlgorithmFactory.cs, src/JWT/Algorithms/IAlgorithmFactory.cs, src/JWT/Algorithms/RSAlgorithmFactory.cs, src/JWT/IAlgorithmFactory.cs, src/JWT/IJwtDecoder.cs, src/JWT/JWT.csproj, src/JWT/JwtDecoder.cs, src/JWT/JwtEncoder.cs, src/JWT/JwtValidator.cs
=> Adding IAlgFactory to master (v3) branch

JWT.nuspec, src/JWT/JwtValidator.cs
Back-porting #111
* Implementing constant-time comparison in JwtValidator 
* Bumping nuget version
=> Implementing constant-time comparison in JwtValidator for v2 branch

JWT.sln.DotSettings, src/JWT/JWT.csproj, src/JWT/Serializers/JsonNetSerializer.cs, tests/JWT.Tests.Common/JwtDecoderTest.cs, tests/JWT.Tests.Common/JwtEncoderTest.cs
Addresses #119.
* Adding to JsonNetSerializer ctor accepting JsonSerializer
* Removing the beta prefix from nuget version
* Replacing xml docs on methods with `<inheritdoc />`
* Soring usings in tests
=> Adding to JsonNetSerializer ctor accepting JsonSerializer

src/JWT/Algorithms/RSAlgorithmFactory.cs, src/JWT/JwtDecoder.cs, tests/JWT.Tests.Common/TestCategory.cs, tests/JWT.Tests.Common/TestData.cs, tests/JWT.Tests.Core/JwtSecurityTest.cs
Added security tests based on [OWASP JWT recommendations](https://www.owasp.org/index.php/JSON_Web_Token_(JWT)_Cheat_Sheet_for_Java). 
Found and fixed a vulnerability allowing an attacker to create a HMAC Token for an RSA Decoder.
The fix is in two places.
- JwtDecoder - set _algFactory to default when algorithm factory is not passed in.
- RSAFactory - can only use RSA algorithms.
Resources on the Vulnerabilities:
[OWASP JWT Recommendations](https://www.owasp.org/index.php/JSON_Web_Token_(JWT)_Cheat_Sheet_for_Java)
[JWT Critical Vulnerabilities](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/)
[JWT Token Editor](https://jwt.io/)
=> OWASP Security Tests and Fixes

.gitignore, tools/packages.config
Pinning the version of cake used, to avoid any changes that might occur if cake is updated. (see [here](http://cakebuild.net/docs/tutorials/pinning-cake-version))
=> Pin cake version

src/JWT/JWT.csproj
- Targeting .NET 4.5.2
- Referencing Json.Net 9.0.1+
- Bumping version to 3.1.0
Resolves #130.
=> Targeting .NET 4.5.2, referencing Json.Net 9.0.1+

src/JWT/JWT.csproj
- Referencing Json.Net 9.0.1
- Fixing output folder settings
- Bumping version to 3.0.3
=> Referencing Json.Net 9.0.1, fixing output folder settings, bumping version to 3.0.3

src/JWT/Builder/ClaimName.cs, src/JWT/Builder/JwtBuilder.cs, src/JWT/IJwtDecoder.cs, src/JWT/IJwtValidator.cs, src/JWT/JWT.csproj, src/JWT/JwtDecoder.cs, src/JWT/JwtValidator.cs, tests/JWT.Tests.Common/JwtBuilderDecodeTest.cs, tests/JWT.Tests.Common/JwtBuilderEncodeTest.cs, tests/JWT.Tests.Common/JwtDecoderTest.cs, tests/JWT.Tests.Common/JwtSecurityTest.cs, tests/JWT.Tests.Common/Models/TestData.cs
In AWS Cognito, they are the ones who create and sign the token. To verify the signature, they are providing multiple keys, one of them used to sign the token, and you don't know which exactly. We need to support adding multiple keys/secrets when decoding and use them to verify the signature.
I've added the new functions:
- `.WithSecrets(string[] keys)` in `JwtBuilder`
- `DecodeToObject(string token, string[] keys, bool verify)` in `JwtDecoder`
=> Support multiple keys for decoding

JWT.sln, NuGet.config, src/JWT/Builder/JwtBuilder.cs, src/JWT/JWT.csproj, tests/JWT.Tests.Common/JwtBuilderDecodeTest.cs, tests/JWT.Tests.Common/JwtBuilderEncodeTest.cs, tests/JWT.Tests.Core/JWT.Tests.Core.csproj, tests/JWT.Tests.NETFramework/JWT.Tests.NETFramework.csproj, tests/JWT.Tests.NETFramework/packages.config
* Adding NuGet.config
* Removing, updating packages
* Using single overload of WithSecret() but with params
* Bumping nuget version
=> Using single overload of WithSecret() but with params

src/JWT/Algorithms/RS256Algorithm.cs, src/JWT/Algorithms/RSAlgorithmFactory.cs, src/JWT/JWT.csproj
This fixes #164
This changes the RS256Algorithm class not to directly take in a Certificate but instead get the RSA/RSACryptoServiceProvider combination.
this is helpful in scenarios such as AWS Cognitio where they provide the modulo and exponent  directly.
=> Change the RS256Algorithm to take in the RSA Service Provider/RSA

README.md, src/JWT/JWT.csproj
Thanks for this library! This PR makes minor tweaks to the targeted frameworks to follow best practice advice 🙂
As you've included a .NET Framework 1.x target, best practice advice is to also include a .NET Standard 2.0 target ([as described in this doc](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)). This avoids bringing in loads of extra packages on non-NETFX frameworks that support .NET Standard 2.0 (e.g. .NET Core)
Unfortunately, .NET Standard support is all screwed up around `net461`. As you already have a `net46` target, all that's needed to fully fix it is the `net472` target.
From a practical point of view, this shouldn't have any impact on consumers, other than simplifying the package graph on .NET Core!
=> Add additional framework targets

src/JWT/Algorithms/RS256Algorithm.cs, src/JWT/JWT.csproj
The messages shown in the exception description are not according to the corresponding variable.
=> Fix Parameters checking in the RS256Algorithm's constructor

src/JWT/Builder/JwtBuilder.cs, src/JWT/JWT.csproj, tests/JWT.Tests.Common/JwtBuilderEncodeTest.cs
While using this library in my company, we would have liked to use the builder to add several claims in a more readable way.
We would have liked to be allowed to do something such as:
```csharp
var token = new JwtBuilder()
.WithAlgorithm(new HMACSHA256Algorithm())
.WithSecret(secret)
.AddClaims({
"my-claim": "my-value",
"my-claim-2": "my-value-2"
})
.Build();
```
I just added a method `AddClaims` allowing the user to pass a IDictionnary of `string: object` in it and add each of its key as a new claim and each of its value as claim value.
=> Add method to add several claims

src/JWT/Algorithms/RSAlgorithmFactory.cs, src/JWT/JWT.csproj
This is my draft implantation for https://github.com/jwt-dotnet/jwt/issues/220
=> Extend RSAlgorithmFactory to support all ctors of RS256Algorithm

JWT.sln, LICENSE.txt, tests/JWT.Tests.Common/JWT.Tests.Common.csproj, tests/JWT.Tests.Common/JwtBuilderDecodeTests.cs, tests/JWT.Tests.Common/JwtBuilderEncodeTests.cs, tests/JWT.Tests.Common/JwtDataTests.cs, tests/JWT.Tests.Common/JwtDecoderTests.cs, tests/JWT.Tests.Common/JwtEncoderTests.cs, tests/JWT.Tests.Common/JwtSecurityTests.cs, tests/JWT.Tests.Common/JwtValidatorTests.cs, tests/JWT.Tests.Common/Models/TestCategory.cs, tests/JWT.Tests.Common/RS256AlgorithmTests.cs, tests/JWT.Tests.Core/JWT.Tests.Core.csproj, tests/JWT.Tests.Core/xunit.runner.json, tests/JWT.Tests.NETFramework/App.config, tests/JWT.Tests.NETFramework/JWT.Tests.NETFramework.csproj, tests/JWT.Tests.NETFramework/packages.config
Rationale:
- Functional parity
- Active development
- First-class support by Microsoft technologies and products (namely: Visual Studio)
- Familiarity of the only maintainer (myself)
Known issues:
- https://github.com/Microsoft/testfx/issues/304
- https://github.com/microsoft/testfx/issues/664
=> Replacing xUnit with MSTest2

src/JWT/Builder/JwtBuilder.cs, src/JWT/IJwtDecoder.cs, src/JWT/IJwtValidator.cs, src/JWT/JWT.csproj, src/JWT/JwtDecoder.cs, src/JWT/JwtValidator.cs, src/JWT/TokenExpiredException.cs
- Replacing methods `Validate(string, string, string)` and `Validate(string, string, string[])` with single `Validate(string, string, params string[])`
- Bumping version to 6.0.0-beta1
=> Siimplyfing methods of Decoder and Validator

src/JWT/Algorithms/RS256Algorithm.cs, src/JWT/JWT.csproj, tests/JWT.Tests.Common/RS256AlgorithmTests.cs
- I'm not sure how to create a certificate _without_ a public key. (I would like to test this scenario, if it's doable).
- Included some tests for
- Certificate has public key only.
- RS256Algorithm can be created with only a public key (existing code, just adding a simple test).
=> RS256 ctor can accept cert with no private key

src/JWT/Builder/JwtBuilderExtensions.cs, src/JWT/JWT.csproj
The `AddClaims()` method does not modify the payload in any way. We can use `IReadOnlyDictionary` instead of ordinary `IDictionary`.
=> Make AddCalims accept an IReadOnlyDictionary

README.md
Fix the README to include the `algorithm` parameter for `JwtDecoder` since that parameter is now mandatory.
Fixes #254
=> Add algorithm argument to decode example in docs

src/JWT/JWT.csproj, src/JWT/JwtDecoder.cs, tests/JWT.Tests.Common/JwtBuilderDecodeTests.cs, tests/JWT.Tests.Common/JwtBuilderEncodeTests.cs, tests/JWT.Tests.Core3/JwtBuilderEndToEndTests.cs
Continuation of #258, cc @stefansolid.
* Made secret optional in Decode() to support asymmetric algorithms
* Bumped version to 6.1.2
=> Made secret optional in Decode() to support asymmetric algorithms

README.md
Sample code for Encoding using the Fluent API in the ReadMe was still using Build() which is obsolete instead of Encode().  Fixed.
Thanks for the great and easy to use library!
=> Fixed sample code in readme to use Encode()

src/JWT/IJsonSerializer.cs, src/JWT/IJwtDecoder.cs, src/JWT/IJwtValidator.cs, src/JWT/JWT.csproj, src/JWT/JwtDecoder.cs
* Made `IJwtDecoder.Decode()` to accept `JwtParts` and `JwtDecoderExtensions.Decode()` to accept `string`
* Bumped version to 7.2.0
=> Reworking IJwtDecoder to accept JwtParts

README.md
Noticed this typo while I was reading through your docs. Obviously a minor issue but figured I'd toss in a PR
=> Fix typo of 'AuthenticationTicket' in readme

src/JWT/Algorithms/ES256Algorithm.cs, src/JWT/Algorithms/ES384Algorithm.cs, src/JWT/Algorithms/ES512Algorithm.cs, src/JWT/Algorithms/HMACSHA256Algorithm.cs, src/JWT/Algorithms/HMACSHA384Algorithm.cs, src/JWT/Algorithms/HMACSHA512Algorithm.cs, src/JWT/Algorithms/RS256Algorithm.cs, src/JWT/Algorithms/RS384Algorithm.cs, src/JWT/Algorithms/RS512Algorithm.cs, src/JWT/Builder/EnumExtensions.cs, src/JWT/Builder/JwtData.cs, src/JWT/Compatibility/String.cs, src/JWT/Exceptions/InvalidTokenPartsException.cs, src/JWT/Internal/EncodingHelper.cs, src/JWT/Internal/StringHelper.cs, src/JWT/JWT.csproj, src/JWT/JwtBase64UrlEncoder.cs, src/JWT/JwtDecoder.cs, src/JWT/JwtEncoder.cs, src/JWT/JwtValidator.cs
- changed call ToString() on enums, and used nameof as this produce const string at compilation time, so const can be processed by JIT in a more efficient way
- reused result of `value.ToString()` in EnumExtensions.GetDescription method
- reduced allocation of unnecessary string.Split result array in JwtData and JwtBase64UrlEncoder
- reused UTF8Encoding instance in EncodingHelper, as I believe it won't change after first usage
- introduced a new method GetBytes in EncodingHelper that allows join two strings directly into bytes array
- reduced Linq usage where it could be replaced with type-specific methods with equivalent behaviour
- reduced yields by joining two Linq Select calls in JwtDecoder.Validate method
- minor comments fixes
- changed version of JWT project to 8.1.6
=> Various performance and memory allocation optimizations

src/JWT/Algorithms/RSAlgorithm.cs, src/JWT/JWT.csproj
This addresses https://github.com/jwt-dotnet/jwt/issues/328 .
The existing preprocessor directive only uses `X509Certificate2.GetRSA...Key()` if targetting NETSTANDARD1_3.
Based on https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.rsacertificateextensions.getrsapublickey?view=net-5.0 , these two methods are supported everywhere except in NETFramework < 4.6
This PR changes the preprocessor branching to list all target frameworks that support `X509Certificate2.GetRSA...Key()`:
* Any netstandard, netcore or net versions
* netframework >= 4.6, that is: 46, 461, 462, 47, 471, 472, 48
=> Use `X509Certificate2.GetRSAPublicKey` in all supported TargetFrameworks

JWT.sln, README.md, src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj, src/JWT.Extensions.DependencyInjection/JWT.Extensions.DependencyInjection.csproj, src/JWT.Extensions.Owin/JWT.Extensions.Owin.csproj, src/JWT/Algorithms/ECDSAAlgorithm.cs, src/JWT/Algorithms/ECDSAAlgorithmFactory.cs, src/JWT/Algorithms/ES256Algorithm.cs, src/JWT/Algorithms/ES384Algorithm.cs, src/JWT/Algorithms/ES512Algorithm.cs, src/JWT/JWT.csproj, src/JWT/Properties/AssemblyInfo.cs, tests/JWT.Extensions.AspNetCore.Tests/JWT.Extensions.AspNetCore.Tests.csproj, tests/JWT.Extensions.DependencyInjection.Tests/JWT.Extensions.DependencyInjection.Tests.csproj, tests/JWT.Extensions.Owin.Tests/JWT.Extensions.Owin.Tests.csproj, tests/JWT.Tests.Common/Algorithms/ECDSAAlgorithmFactoryTests.cs, tests/JWT.Tests.Common/Algorithms/ECDSAAlgorithmTests.cs, tests/JWT.Tests.Common/JWT.Tests.Common.csproj, tests/JWT.Tests.Net35/JWT.Tests.Net35.csproj, tests/JWT.Tests.Net46/JWT.Tests.Net46.csproj, tests/JWT.Tests.Net50/JWT.Tests.Net50.csproj, tests/JWT.Tests.Net60/JWT.Tests.Net60.csproj, tests/JWT.Tests.NetCore2/JWT.Tests.NetCore2.csproj, tests/JWT.Tests.NetCore3/JWT.Tests.NetCore3.csproj
Addresses one of the issues mentioned in #364.
=> Added support for .NET 6

src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj, src/JWT.Extensions.DependencyInjection/JWT.Extensions.DependencyInjection.csproj, src/JWT.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, src/JWT/Algorithms/GenericAlgorithmFactory.cs, src/JWT/Algorithms/HMACSHAAlgorithm.cs, src/JWT/JWT.csproj, tests/JWT.Extensions.DependencyInjection.Tests/ServiceCollectionExtensionsTests.cs
=> Added AddJwtEncoder() accepting IJwtAlgorithm

src/JWT/Builder/JwtBuilder.cs, src/JWT/JWT.csproj, src/JWT/JwtDecoder.cs, tests/JWT.Tests.Common/Builder/JwtBuilderDecodeTests.cs, tests/JWT.Tests.Common/Models/TestData.cs
Added some tests for none algorithm and also implemented that signature MUST not be sent according to spec in:
- https://datatracker.ietf.org/doc/html/rfc7519#section-6
- https://datatracker.ietf.org/doc/html/rfc7518#section-3.6
=> Added some checks for none algorithm

src/JWT/Builder/JwtBuilder.cs
I was trying out your lovely framework, however got a few exceptions, and noticed a typo in the message. I wanted to help by fixing them :)
=> Fixing typos in exception messages

Directory.Build.props, JWT.sln, src/Directory.Build.targets, src/JWT.Extensions.AspNetCore/Factories/DefaultIdentityFactory.cs, src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj, src/JWT.Extensions.AspNetCore/JwtAuthenticationOptions.cs, src/JWT.Extensions.DependencyInjection/JWT.Extensions.DependencyInjection.csproj, src/JWT.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, src/JWT/Algorithms/RSAlgorithm.cs, src/JWT/Builder/JwtBuilder.cs, src/JWT/Builder/JwtHeader.cs, src/JWT/JWT.csproj, src/JWT/Properties/AssemblyInfo.cs, src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs, src/JWT/Serializers/JsonNetSerializer.cs, src/JWT/Serializers/JsonSerializerFactory.cs, src/JWT/Serializers/SystemTextSerializer.cs, tests/JWT.Extensions.AspNetCore.Tests/JWT.Extensions.AspNetCore.Tests.csproj, tests/JWT.Extensions.AspNetCore.Tests/JwtAuthenticationHandlerTests.cs, tests/JWT.Extensions.DependencyInjection.Tests/JWT.Extensions.DependencyInjection.Tests.csproj, tests/JWT.Tests.Common/Builder/JwtBuilderDecodeTests.cs, tests/JWT.Tests.Common/JwtDecoderTests.cs, tests/JWT.Tests.Common/JwtEncoderTests.cs, tests/JWT.Tests.Common/JwtSecurityTests.cs, tests/JWT.Tests.Common/JwtValidatorTests.cs, tests/JWT.Tests.Common/Models/TestData.cs, tests/JWT.Tests.Net60/JWT.Tests.Net60.csproj, tests/JWT.Tests.NetCore3/JWT.Tests.NetCore3.csproj
=> Replaced NewtonSoft.Json with System.Text.Json

tests/JWT.Tests.Common/Algorithms/RSAlgorithmFactoryTests.cs, tests/JWT.Tests.Common/Algorithms/RSAlgorithmTests.cs
Will probably be needed for #407 
Unless this fix is applied the tests fail with this error when running on arch linux:
```
Test method JWT.Tests.Algorithms.RSAlgorithmTests.Ctor_Should_Throw_Exception_When_PrivateKey_Is_Null threw exception: 
AutoFixture.ObjectCreationExceptionWithPath: AutoFixture was unable to create an instance from System.Security.Cryptography.RSACryptoServiceProvider because creation unexpectedly failed with exception. Please refer to the inner exception to investigate the root cause of the failure.
Request path:
System.Security.Cryptography.RSACryptoServiceProvider
Inner exception messages:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Security.Cryptography.CryptographicException: Specified key is not …
```
=> Fixed tests, build on Arch Linux

src/JWT/JWT.csproj, src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs, src/JWT/Serializers/SystemTextSerializer.cs
I posted about our finding of the bug #439 in the repo from where I found the code for handling Dictionary<string, object> serialization.
https://github.com/joseftw/JOS.STJ.DictionaryStringObjectJsonConverter/issues/2
Apparently the converter is only needed when reading serialized data so we can cleanup our code a bit.
=> DictionaryStringObjectJsonConverter is only needed when deserializing

.editorconfig, CHANGELOG.md, JWT.sln, JWT.sln.DotSettings, src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj, src/JWT.Extensions.DependencyInjection/JWT.Extensions.DependencyInjection.csproj, src/JWT/Builder/JwtData.cs, src/JWT/Builder/JwtHeader.cs, src/JWT/JWT.csproj, src/JWT/JwtDecoder.cs, tests/Directory.Build.props, tests/JWT.Extensions.AspNetCore.Tests/JWT.Extensions.AspNetCore.Tests.csproj, tests/JWT.Extensions.DependencyInjection.Tests/JWT.Extensions.DependencyInjection.Tests.csproj, tests/JWT.Tests.Common/Builder/JwtBuilderDecodeTests.cs
=> Fixed deserializing JWT header

CHANGELOG.md
Changing the default serializer is a breaking change and should be explicitly called out.
We were hit by outages in production because while I had carefully reviewed the changelog, this particular change was not mentioned, and therefore not tested. (Shame on us for not having a sufficiently comprehensive test suite to catch this, of course.)
=> Added note about breaking changes in 10.0.0

CHANGELOG.md, src/JWT/JWT.csproj, src/JWT/ValidationParameters.cs, tests/JWT.Tests.Common/JwtValidatorTests.cs
The constructor for ValidationParameters was private, which produces compile errors for the examples on the main page and prevents them from being used (https://github.com/jwt-dotnet/jwt#turning-off-parts-of-token-validation, https://github.com/jwt-dotnet/jwt#or-using-the-fluent-builder-api-4). Making the constructor public makes them valid. It's possible to use the "With" method and the "Default" or "None" properties, but it is cumbersome.
=> Made ctor of ValidationParameters public

README.md
=> Fixed sample for Encode() in README.md

src/JWT/JwtDecoder.cs, tests/JWT.Tests.Common/JwtDecoderTests.cs
=> Update JwtDecoder to prevent NullReferenceException in AllKeysHaveValues()

src/JWT/Algorithms/ECDSAAlgorithmFactory.cs, src/JWT/Algorithms/RSAlgorithmFactory.cs, src/JWT/Builder/JwtBuilder.cs, src/JWT/IJwtEncoder.cs, src/JWT/JwtValidator.cs
To better follow the naming convention and improve code readability, the null checks in JwtBuilder.cs have been updated from `is object` to `is not null`.
=> Refactor null checks with 'is not null' in JwtBuilder

CHANGELOG.md, src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj, src/JWT.Extensions.AspNetCore/JwtAuthenticationEvents.cs, src/JWT.Extensions.AspNetCore/JwtAuthenticationHandler.cs, src/JWT.Extensions.AspNetCore/JwtAuthenticationOptions.cs, tests/JWT.Extensions.AspNetCore.Tests/JwtAuthenticationEventsIntegrationTests.cs
I was integrating the beta build into my project and noticed that I failed to make the events async/await able. This is preventing me from digging into my database to verify attributes about the JWT token in my custom Event Type.
I was careful to avoid doing any actual awaits in the framework to try and minimize the amount of "task switching" that the internal framework is doing.
=> Made events async

.pipelines/build.yml
Resolves #505 .
CI build is now configured with deterministic build flag. Artifacts contain nuget packages with proper flags:
=> Make CI build deterministic

CHANGELOG.md, src/JWT/JWT.csproj
Upgraded Nuget ref for System.Text.Json
[JsonExtensionData] is not used, but its annoying that there are vulnerabilities in refs
=> Updated System.Text.Json to version 9.0.0
