- JWT/JWT.cs
I've added a method to deserialize to an object which you will then be able to have something like:
```
public class JwtToken
{
public string Issuer { get; set; }
public string Audience { get; set; }
public IEnumerable<Claim> Claims { get; set; }
public DateTime Expiry { get; set; }
}
```
> Deserialze to object

- JWT.Tests/DecodeTests.cs
- JWT.Tests/EncodeTests.cs
- JWT.Tests/JWT.Tests.csproj
- JWT.Tests/Serializers.cs
- JWT.Tests/packages.config
- JWT/DefaultJsonSerializer.cs
- JWT/IJsonSerializer.cs
- JWT/JWT.cs
- JWT/JWT.csproj
- README.md
New pull request for #21.  When I consolidated the commits it auto closed the original.
I've removed Log and added Unit Tests.
> Add JsonSerializer

- JWT/JWT.cs
> Remove unnecessary ToArray()

- src/JWT/JWT.cs
- src/JWT/JwtHashAlgorithm.cs
- src/JWT/SignatureVerificationException.cs
- src/JWT/TokenExpiredException.cs
... and Refactor SignatureVerificationException to use properties instead of the Data collection directly
> TokenExpiredException inherits from SignatureVerificationException + Refactor 

- src/JWT/Algorithms/HMACSHA384Algorithm.cs
- src/JWT/Algorithms/HMACSHA512Algorithm.cs
> Using correct HMACSHA in corresponding IAlgorithm implementation

- build.cake
- tests/JWT.Tests.NETFramework/JWT.Tests.NETFramework.csproj
Closes https://github.com/jwt-dotnet/jwt/issues/95
> Fix tests for both platforms

- src/JWT/AlgorithmFactory.cs
- src/JWT/Algorithms/HMACSHA256Algorithm.cs
- src/JWT/Algorithms/HMACSHA384Algorithm.cs
- src/JWT/Algorithms/HMACSHA512Algorithm.cs
- src/JWT/Algorithms/RS256Algorithm.cs
- src/JWT/IBase64UrlEncoder.cs
- src/JWT/IDateTimeProvider.cs
- src/JWT/IJwtAlgorithm.cs
- src/JWT/IJwtDecoder.cs
- src/JWT/IJwtEncoder.cs
- src/JWT/IJwtValidator.cs
- src/JWT/JwtBase64UrlEncoder.cs
- src/JWT/JwtDecoder.cs
- src/JWT/JwtEncoder.cs
- src/JWT/JwtHashAlgorithm.cs
- src/JWT/JwtValidator.cs
- src/JWT/Serializers/JsonNetSerializer.cs
- src/JWT/SignatureVerificationException.cs
- src/JWT/TokenExpiredException.cs
- src/JWT/UtcDateTimeProvider.cs
Added XML documentation missing in files.
> Added missing xml documentation

- .gitignore
- tests/JWT.Tests.Core/JWT.Tests.Core.csproj
- tests/JWT.Tests.Core/xunit.runner.json
- tests/JWT.Tests.NETFramework/App.config
- tests/JWT.Tests.NETFramework/JWT.Tests.NETFramework.csproj
* Updating .gitignore
* Adding xunit.methodDisplay=method to test projects
> Updating misc files: gitignore, test projects app settings

- src/JWT/JWT.csproj
- src/JWT/JwtValidator.cs
* Implementing constant-time comparison in JwtValidator 
* Bumping nuget version
> Implementing constant-time comparison in JwtValidator

- .gitignore
- JWT.sln
- appveyor.yml
- build.cake
- build.ps1
- tests/JWT.Tests/packages.config
Cherry-picking Cake/AppVeyor related commits from master to v2.
> Adding support of AppVeyor to v2 branch

- README.md
> Added a custom JsonSerializer settings example.

- src/JWT/IBase64UrlEncoder.cs
- src/JWT/IDateTimeProvider.cs
- src/JWT/IJwtDecoder.cs
- src/JWT/IJwtEncoder.cs
- src/JWT/IJwtValidator.cs
- src/JWT/JWT.csproj
- src/JWT/Jwt.cs
- src/JWT/JwtBase64UrlEncoder.cs
- src/JWT/JwtDecoder.cs
- src/JWT/JwtEncoder.cs
- src/JWT/JwtParts.cs
- src/JWT/JwtValidator.cs
- src/JWT/SignatureVerificationException.cs
- src/JWT/TokenExpiredException.cs
Add the missing overloads form #138. 
For better code a add a little Enum for the different parts of an JWT. Maybe we can put this enum to a better place. Lets us discuss about this.
I add some regions in the IJwtDecoder Interface so you can faster find the right methods.
> Adding overloads for Decode()

- src/JWT/JWT.csproj
> Downgrading to NET46

- src/JWT/IDateTimeProvider.cs
- src/JWT/JWT.csproj
- src/JWT/UnixEpoch.cs
- src/JWT/UtcDateTimeProvider.cs
Resolves #145.
- DateTime provider to return DateTimeOffset
- Bumping nuget version to beta2
> DateTime provider to return DateTimeOffset

- README.md
- src/JWT/JwtValidator.cs
As mentioned in https://github.com/jwt-dotnet/jwt/issues/134#issuecomment-417680984.
> Update links to latest RFC

- src/JWT/Algorithms/IJwtAlgorithm.cs
- src/JWT/Builder/JwtBuilder.cs
- src/JWT/JWT.csproj
>  Adding to JwtBuilder overload of WithSecrets() accepting params byte[][] 

- README.md
original sample does not work with latest dll
> Update validate token expiration sample code

- src/JWT/JWT.csproj
- src/JWT/JwtEncoder.cs
> Make a copy of extra headers before modifying them

- src/Directory.Build.props
- src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj
- src/JWT.Extensions.Owin/JWT.Extensions.Owin.csproj
- src/JWT/JWT.csproj
* Set EnableSourceLink=true
Resolves #242.
> Update Directory.Build.props to enable SourceLink

- src/JWT/Builder/JwtBuilder.cs
- src/JWT/Builder/JwtBuilderExtensions.cs
- src/JWT/JWT.csproj
- src/JWT/UnixEpoch.cs
> Adds, changes extension methods for JwtBuilder working with dates

- src/JWT/JWT.csproj
- src/JWT/JwtDecoder.cs
- tests/JWT.Tests.Common/Builder/JwtBuilderDecodeTests.cs
* Allowed to verify signature with only public key
* Bumped version to 6.1.3
* Updated test
> Allowed to verify signature with only public key

- src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj
- src/JWT.Extensions.AspNetCore/JwtAuthenticationHandler.cs
- src/JWT.Extensions.AspNetCore/JwtAuthenticationOptions.cs
* Improved logging in JwtAuthenticationHandler
* Bumped version to 7.1.0-beta1
> Improved logging in JwtAuthenticationHandler

- src/JWT/JWT.csproj
> Bumped version to 7.1.0, dropped the beta suffix

- src/JWT/JWT.csproj
- src/JWT/JwtEncoder.cs
- tests/JWT.Tests.Common/JwtEncoderTests.cs
- tests/JWT.Tests.Common/Models/TestData.cs
https://github.com/jwt-dotnet/jwt/issues/284
JwtEncoder checks if 'typ' header is presented in an extra headers before adding default value
> Custom typ header

- src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj
- src/JWT.Extensions.AspNetCore/JwtAuthenticationHandler.cs
> Fixed logging in JwtAuthenticationHandler

- src/JWT/Internal/EncodingHelper.cs
- src/JWT/JWT.csproj
- tests/JWT.Tests.Common/Builder/JwtBuilderEncodeTests.cs
> Removed UTF8 BOM

- src/JWT/Builder/JwtHeader.cs
- src/JWT/JWT.csproj
- tests/JWT.Tests.Core3/JwtBuilderEndToEndTests.cs
> Fixed wrongly defined x5c property in JwtHeader, inluding unit test.

- src/JWT/JWT.csproj
- src/JWT/JwtValidator.cs
- tests/JWT.Tests.Common/JwtValidatorTests.cs
- tests/JWT.Tests.Common/Models/TestData.cs
- tests/JWT.Tests.Common/Stubs/StaticDateTimeProvider.cs
> Added time margin to JwtValidator

- src/JWT/Algorithms/HMACSHA384Algorithm.cs
- src/JWT/JWT.csproj
> Used correct algorithm HMACSHA384 in HMACSHA384Algorithm class

- src/JWT/JWT.csproj
- src/JWT/JwtEncoder.cs
It reduces a few unneeded allocations.
> Memory optimization in JwtEncoder.Encode method

- src/JWT/Algorithms/ECDSAAlgorithm.cs
- src/JWT/Algorithms/ECDSAAlgorithmFactory.cs
- src/JWT/Algorithms/ES256Algorithm.cs
- src/JWT/Algorithms/ES384Algorithm.cs
- src/JWT/Algorithms/ES512Algorithm.cs
- src/JWT/JWT.csproj
- tests/JWT.Tests.Common/Algorithms/ECDSAAlgorithmFactoryTests.cs
- tests/JWT.Tests.Common/Algorithms/ECDSAAlgorithmTests.cs
> Fixed #ifdef for .NET 5.0

- src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj
- src/JWT.Extensions.Owin/JWT.Extensions.Owin.csproj
- src/JWT/JWT.csproj
> Upgraded Json.Net to 10.0.3

- Updated README.md
Adding the notes to the "Register middleware to validate JWT" section since it was not clear that it was not implemented yet until I read the Jwt.Net OWIN section.
> Update Updated README.md

- src/JWT/JWT.csproj
- tests/JWT.Tests.Net50/JWT.Tests.Net50.csproj
> Used TargetFramework net5.0

- README.md
- src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj
- src/JWT/JWT.csproj
- src/JWT/JwtDecoder.cs
> Throwing more readable exceptions for missing Validator or Algorithm factory

- src/JWT/Algorithms/JwtAlgorithmName.cs
- src/JWT/Algorithms/RS1024Algorithm.cs
- src/JWT/Algorithms/RS2048Algorithm.cs
- src/JWT/Algorithms/RS4096Algorithm.cs
- src/JWT/Algorithms/RSAlgorithmFactory.cs
- src/JWT/JWT.csproj
- tests/JWT.Tests.Common/Algorithms/RSAlgorithmFactoryTests.cs
- tests/JWT.Tests.Common/Algorithms/RSAlgorithmTests.cs
- tests/JWT.Tests.Common/Builder/JwtBuilderDecodeTests.cs
- tests/JWT.Tests.Common/Builder/JwtBuilderEncodeTests.cs
Adds implementation of the RSA algorithm with 1024, 2048 and 4096 lengths for the future.
> Added RSA algorithm for 1024, 2048, 4096 key lengths

- src/JWT/IBase64UrlEncoder.cs
- src/JWT/JWT.csproj
- src/JWT/JwtBase64UrlEncoder.cs
- src/JWT/JwtDecoder.cs
- src/JWT/JwtEncoder.cs
- src/JWT/JwtValidator.cs
- tests/JWT.Tests.Common/JWT.Tests.Common.csproj
- tests/JWT.Tests.Common/JwtValidatorTests.cs
> Made JwtValidator.GetException() public

- .pipelines/build.yml
> Switched build pipeline back to windows-2019

- src/JWT/Algorithms/JwtAlgorithmFactory.cs
> Added null-check to JwtAlgorithmFactory

- .pipelines/build.yml
- src/JWT/JWT.csproj
Reverts #381. See also https://github.com/actions/virtual-environments/issues/5372
> Switched build pipeline back to windows-latest

- src/JWT/Algorithms/NoneAlgorithm.cs
- src/JWT/JwtDecoder.cs
> Added null-checks to JwtDecoder.Validate()

- src/JWT/Builder/JwtBuilder.cs
- src/JWT/JWT.csproj
- tests/JWT.Tests.Common/Builder/JwtBuilderEncodeTests.cs
> Fixed JwtBuilder.Encode() with custom factory

- src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj
- src/JWT.Extensions.DependencyInjection/JWT.Extensions.DependencyInjection.csproj
- src/JWT/JWT.csproj
I assume PackageLicenseExpression is the wanted tag, since nuget is currently missing license information (see https://www.nuget.org/packages/JWT/)
> PackageLicense to PackageLicenseExpression

- .pipelines/build.yml
- README.md
used the program pandoc:
pandoc -s --toc README.md -o README.md
https://pandoc.org/index.html
> Added a Table of Contents on the README.md

- src/JWT/JWT.csproj
- src/JWT/Serializers/Converters/DictionaryStringObjectJsonConverter.cs
- src/JWT/Serializers/DelegateJsonSerializerFactory.cs
- tests/JWT.Tests.Common/Builder/JwtBuilderEncodeTests.cs
> Fixed handling IEnumerable by DictionaryStringObjectJsonConverter

- .pipelines/build.yml
- JWT.sln
- src/JWT/Algorithms/ECDSAAlgorithm.cs
- src/JWT/Algorithms/ECDSAAlgorithmFactory.cs
- src/JWT/Algorithms/ES256Algorithm.cs
- src/JWT/Algorithms/ES384Algorithm.cs
- src/JWT/Algorithms/ES512Algorithm.cs
- src/JWT/Properties/AssemblyInfo.cs
- tests/JWT.Tests.Common/Algorithms/ECDSAAlgorithmFactoryTests.cs
- tests/JWT.Tests.Common/Algorithms/ECDSAAlgorithmTests.cs
- tests/JWT.Tests.Common/Builder/JwtBuilderEncodeTests.cs
- tests/JWT.Tests.Common/JwtBuilderEndToEndTests.cs
- tests/JWT.Tests.Net60/TargetFrameworkTests.cs
- tests/JWT.Tests.Net70/JWT.Tests.Net70.csproj
> Added unit tests for .NET 7

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Resolves #425.
Added github templates
> Bug, feature and request templates

- src/JWT/JWT.csproj
> Added README into NuGet package for JWT

- .pipelines/build.yml
- CHANGELOG.md
- Directory.Build.props
- JWT.sln
- JWT.sln.DotSettings
- src/JWT.Extensions.AspNetCore/JWT.Extensions.AspNetCore.csproj
- src/JWT.Extensions.DependencyInjection/JWT.Extensions.DependencyInjection.csproj
- src/JWT/JWT.csproj
- src/JWT/Properties/AssemblyInfo.cs
- tests/JWT.Extensions.AspNetCore.Tests/JWT.Extensions.AspNetCore.Tests.csproj
- tests/JWT.Extensions.DependencyInjection.Tests/JWT.Extensions.DependencyInjection.Tests.csproj
- tests/JWT.Tests.Net80/JWT.Tests.Net80.csproj
- Replaced .NET 7 with .NET 8 whenever applicable
> Replaced .NET 7 with .NET 8

- CHANGELOG.md
- src/JWT/JWT.csproj
- tests/Directory.Build.props
- tests/JWT.Extensions.AspNetCore.Tests/JWT.Extensions.AspNetCore.Tests.csproj
- Updated System.Text.Json to version 8.0.4
- Updated various build-time dependencies
A summary of the changes and which issue it resolves.
> Updated NuGet packages

- README.md
Reverts #499.
A summary of the changes and which issue it resolves.
> Update README.md with sponsor information

- src/JWT/Serializers/SystemTextSerializer.cs
Resolves #503.
A summary of the changes and which issue it resolves.
> Update XML comment in SystemTextSerializer.cs

- tests/Directory.Build.props
> Updated MSTest.* from 3.7.3 to 3.8.0

- .github/dependabot.yml
Configured Dependabot to update MSTest packages together.
> Added MSTest to dependabot.yml
